name: graphql_flutter tests case

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '2.10.5'
      - name: Install dependencies
        run: make dep
      - name: Tests
        run: make ci_check_flutter